### ISSUE TITLE
No tests detected since TUnitRunner update

### ISSUE THREAD

**Issue by ArkaHnat** [thomhurst/ModularPipelines#519]
Since commit **705c4e0a355bf07f77d14a75bf83298a31e68aa9** there is following error during test discovery:

```
========== Starting test discovery ==========
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo)
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs:line 223
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyDiscoveryManager.cs:line 149
Microsoft.VisualStudio.TestPlatform.ObjectModel.TestPlatformException: Could not find testhost
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Hosting.DotnetTestHostManager.GetTestHostProcessStartInfo(IEnumerable`1 sources, IDictionary`2 environmentVariables, TestRunnerConnectionInfo connectionInfo) in /_/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs:line 410
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyOperationManager.SetupChannel(IEnumerable`1 sources, String runSettings) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyOperationManager.cs:line 182
   at Microsoft.VisualStudio.TestPlatform.CrossPlatEngine.Client.ProxyDiscoveryManager.InitializeDiscovery(DiscoveryCriteria discoveryCriteria, ITestDiscoveryEventsHandler2 eventHandler, Boolean skipDefaultAdapters) in /_/src/Microsoft.TestPlatform.CrossPlatEngine/Client/ProxyDiscoveryManager.cs:line 130
NUnit Adapter 4.5.0.0: Test discovery starting
NUnit Adapter 4.5.0.0: Test discovery complete
========== Test discovery aborted: 4 Tests found in 2.2 sec ==========
```

After attempt to add Unit.TestAdapter and Microsoft.NET.Test.Sdk following error occured:
```
========== Starting test discovery ==========
An exception occurred while test discoverer 'TestDiscoverer' was loading tests. Exception: Could not load type 'TUnit.Core.TestDetails' from assembly 'TUnit.Core, Version=0.1.288.0, Culture=neutral, PublicKeyToken=null'.
No test is available in F:\Dev\ModularPipelines\test\ModularPipelines.UnitTests\bin\Debug\net7.0\ModularPipelines.UnitTests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
```

Error occurs in Microsoft Visual Studio Professional 2022 (64-bit) v17.10.3

**Comment by thomhurst** [comment]
Hey @ArkaHnat . The tests are using a new test runner that is technically still in preview from Microsoft (but pretty stable from experience). You might need the preview version of visual studio, I'm not sure. But you can go into the preview options and enable the new testing platform server setting. Once this is done, restart visual studio, build the solution and the tests should start.

The Test adapter package is now a relic from the old style of runner, so I'll make a note to deprecate it. And the Microsoft testing SDK is also just for the old style now, and won't be required going forward.

Unfortunately if you're using an ide like rider I don't think they've implemented support for the new test runner yet, but they're still working on it

**Comment by ArkaHnat** [comment]
Worked like a charm
